name: Deploy to Cloud Run (V2)

on:
  workflow_dispatch:  # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v3

      # Authenticate
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth  configure-docker europe-west1-docker.pkg.dev

      - name: Build image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bookstore-api/bookstore-api:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -f Dockerfile.staging -t $IMAGE .

      - name: Push image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run (Octane)
        run: |
          gcloud run deploy bookstore-api \
            --image "$IMAGE" \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --network=default \
            --subnet=default \
            --vpc-egress=private-ranges-only \
            --set-secrets DB_PASSWORD=bookstore-db-pwd:latest \
            --set-secrets APP_KEY=APP_KEY:latest \
            --set-secrets JWT_SECRET=JWT_SECRET:latest \
            --set-env-vars APP_ENV=development \
            --set-env-vars DB_USERNAME=bookstore \
            --set-env-vars DB_HOST=10.132.0.2 \
            --set-env-vars DB_PORT=5432 \
            --set-env-vars DB_CONNECTION=pgsql \
            --set-env-vars DB_DATABASE=bookstore \
            --set-env-vars DB_SSLMODE=disable \
            --set-env-vars LOG_CHANNEL=database \
            --set-env-vars CACHE_STORE=array \
            --set-env-vars FILESYSTEM_DISK=gcs \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars GCP_BUCKET=bookstore-laravel \
            --set-env-vars VISIBILITY=public \
            --set-env-vars L5_SWAGGER_USE_ABSOLUTE_PATH=false \
            --set-env-vars APP_URL=https://store-manager-fe-m9rm-ax7j9ku8o-demis-projects-21e0bf22.vercel.app


