name: Run Migrations (Manual)

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build & Push migration image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bookstore-api-migrations/bookstore-api-migrations:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -f Dockerfile.migrate -t $IMAGE .
          docker push $IMAGE

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy bookstore-api-migrations \
            --image "$IMAGE" \
            --region europe-west1 \
            --set-secrets DB_PASSWORD=bookstore-db-pwd:latest \
            --set-secrets APP_KEY=APP_KEY:latest \
            --set-secrets JWT_SECRET=JWT_SECRET:latest \
            --set-env-vars APP_ENV=development \
            --set-env-vars DB_USERNAME=bookstore_user \
            --set-env-vars DB_HOST=/cloudsql/bookstore-staging:europe-west1:free-trial-first-project \
            --set-env-vars DB_SOCKET=/cloudsql/bookstore-staging:europe-west1:free-trial-first-project \
            --set-env-vars DB_PORT=3306 \
            --set-env-vars DB_CONNECTION=mysql \
            --set-env-vars DB_DATABASE=bookstore \
            --set-env-vars LOG_CHANNEL=stderr \
            --command php \
            --args "artisan,migrate,--force"

      - name: Execute Job
        run: |
          gcloud run jobs execute bookstore-api-migrations \
            --region europe-west1

      - name: Tail Logs
        run: |
          gcloud run jobs logs tail bookstore-api-migrations \
            --region europe-west1 \
            --follow
