name: Run Migrations (Manual)

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build & Push migration image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bookstore-api-migrations/bookstore-api-migrations:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -f Dockerfile.migrate -t $IMAGE .
          docker push $IMAGE

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy bookstore-api-migrations \
            --image "$IMAGE" \
            --region europe-west1 \
            --network=default \
            --subnet=default \
            --vpc-egress=private-ranges-only \
            --set-secrets DB_PASSWORD=bookstore-db-pwd:latest \
            --set-secrets APP_KEY=APP_KEY:latest \
            --set-secrets JWT_SECRET=JWT_SECRET:latest \
            --set-env-vars APP_ENV=development \
            --set-env-vars DB_USERNAME=bookstore \
            --set-env-vars DB_HOST=10.132.0.2 \
            --set-env-vars DB_PORT=5432 \
            --set-env-vars DB_CONNECTION=pgsql \
            --set-env-vars DB_DATABASE=bookstore \
            --set-env-vars LOG_CHANNEL=database \
            --set-env-vars CACHE_STORE=array \
            --set-env-vars FILESYSTEM_DISK=gcs \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars GCP_BUCKET=bookstore-laravel \
            --set-env-vars VISIBILITY=public \
            --set-env-vars APP_URL=https://store-manager-fe-m9rm-ax7j9ku8o-demis-projects-21e0bf22.vercel.app \
            --command php \
            --args "artisan,migrate:fresh,--seed"

      - name: Execute Job
        run: |
          gcloud run jobs execute bookstore-api-migrations \
            --region europe-west1
